### ISSUE TITLE
Hostname does not get recognized because of Typo Hostname -> HostName

### ISSUE THREAD

**Issue by novski** [insectos/node-red-ssh-exec#12]
There is a Typo in this line:
https://github.com/insectos/ssh-exec/blob/9b5822be1caf32982a3b1ef287ab04325a5dce33/ssh-exec/utils.js#L97
Change it to `host: hostCfg.HostName,` and it will pick up the Hostname if defined as in the [official specification](https://www.ssh.com/academy/ssh/config).
Or maybe it is more save to let both be accepted as some other [doc's](https://man7.org/linux/man-pages/man5/ssh_config.5.html) use "Hostname"...
`host: hostCfg.HostName ?? host: hostCfg.HostName : host: hostCfg.Hostname,`

If anybody stumbles over this issue, for now it is possible to use `Hostname` in the config file..

**Comment by Stwissel** [comment]
solved
