### ISSUE TITLE
Demo flow should use 'ls --color=never -al' to prevent control characters send by SSH connection

### ISSUE THREAD

**Issue by juggledad** [insectos/node-red-ssh-exec#3]
**Is your feature request related to a problem? Please describe.**
The sample flow returns control characters when ssh'ing to a Mac due to color

**Describe the solution you'd like**
change teh demo flow to use `ls --color=never -al` which will remove teh color control characters

**Describe alternatives you've considered**
manually change the demo flow

**Additional context**
not at this time

**Comment by Stwissel** [comment]
Good catch, I'll update the demo

**Comment by Stwissel** [comment]
fixed in 0.3.2
